# roles/node_exporter/defaults/main.yml
---
# Node Exporter version & architecture
node_exporter_version: "1.10.2"
node_exporter_os: "linux"
node_exporter_arch: "amd64"

# Dynamic download URL (update version above to upgrade)
node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.{{ node_exporter_os }}-{{ node_exporter_arch }}.tar.gz"

# Installation paths
node_exporter_install_dir: /usr/local/bin
node_exporter_tmp_dir: /tmp
node_exporter_service_path: /etc/systemd/system/node_exporter.service

# User & service info
node_exporter_user: node_exporter
node_exporter_service_name: node_exporter